package.json

Needed for https://github.com/bethinkpl/wnl-platform/pull/3482

Allow node 16

---

package.json
yarn.lock

Upgrade SB

---

.storybook/preview.js
lib/js/components/Cards/CardExpandable/CardExpandable.vue
lib/js/components/SectionHeader/SectionHeader.consts.ts
lib/js/components/SectionHeader/SectionHeader.stories.mdx
lib/js/components/SectionHeader/SectionHeader.vue
lib/js/components/SectionHeader/index.ts
lib/js/index.ts

- https://bethink.atlassian.net/browse/IT-4469
- https://www.figma.com/file/HFY6waq7kWsr3rj8a0ghXZ/INI-115-Panel-admina?node-id=302%3A92840
- https://wnl-design-system-preview.s3.eu-central-1.amazonaws.com/IT-4469/index.html?path=/story/components-sectionheader--interactive&cb=4

IT-4469 | Add SectionHeader

---

lib/js/components/Buttons/IconButton/IconButton.consts.ts
lib/js/components/Buttons/IconButton/IconButton.vue
lib/js/components/Icon/Icon.consts.ts
lib/js/components/Pill/Pill.consts.ts
lib/js/components/Pill/Pill.spec.ts
lib/js/components/Pill/Pill.stories.mdx
lib/js/components/Pill/Pill.vue
lib/js/components/Pill/index.ts
lib/js/index.ts
lib/styles/components/_icons.scss
lib/styles/settings/_buttons.scss
lib/styles/settings/_icons.scss

Additionally:
* new `IconButton` size: `XX_SMALL`
* new `IconButton` color: `FAIL`
* new `Icon` size: `XXX_SMALL`

IT-4616 | Pill

---

lib/js/components/Tile/Tile.consts.ts
lib/js/components/Tile/Tile.spec.ts
lib/js/components/Tile/Tile.stories.mdx
lib/js/components/Tile/Tile.vue
lib/js/components/Tile/index.ts
lib/js/index.ts

IT-4624 Tile component has a color prop

---

lib/js/components/Banner/Banner.stories.mdx
lib/js/components/Banner/Banner.vue

Needed for https://bethink.atlassian.net/browse/IT-4661 / https://github.com/bethinkpl/wnl-platform/pull/3872
Mostly copied from https://github.com/bethinkpl/design-system/blob/88e51d6aa0466e39d07dbb8b57a3633b0d65868d/lib/js/components/Cards/CardExpandable/CardExpandable.vue

IT-4661 | Expose Banner expanded state

---

lib/js/components/SelectList/SelectList.vue

https://bethink.atlassian.net/browse/IT-4682

IT-4682 | Add ripple to SelectList

---

lib/styles/components/_buttons.scss

rule was in ".outline", now is in ":not .text"

Fix rounded filled button -> 

---

lib/js/components/TagList/TagList.consts.ts
lib/js/components/TagList/TagList.stories.ts
lib/js/components/TagList/TagList.vue
lib/js/components/TagList/index.ts
lib/js/index.ts

https://www.figma.com/file/WeJCbVlnkL9HmEcoBpu5NU/LMS---Specific-Components-%26-Limbo?node-id=464%3A26198

IT-4632 | Add TagList component

---

lib/js/components/Banner/Banner.vue

fix for https://bethinkteam.slack.com/archives/C012R8RM3A4/p1665046299978709?thread_ts=1664986760.598829&cid=C012R8RM3A4

add flex-grow for rightSlot on mobile in Banner

---

README.md
package.json

https://www.npmjs.com/package/@bethinkpl/design-system
It will allow us to install design-system in wnl-platform without bumping into issue with fontawesome authorization. More details in https://github.com/bethinkpl/wnl-platform/pull/3946#issuecomment-1221550741.

IT-4359 | Publish to npm

---

lib/js/components/Badges/BadgeScore/BadgeScore.vue
lib/js/components/Banner/Banner.vue
lib/js/components/Buttons/Button/Button.vue
lib/js/components/Buttons/IconButton/IconButton.vue
lib/js/components/Drawer/Drawer.vue
lib/js/components/Dropdown/Dropdown.vue
lib/js/components/Icon/Icon.vue
lib/js/components/Pill/Pill.vue
lib/js/components/PopOver/PopOver.vue
lib/js/components/ProgressBar/ProgressBar.vue
lib/js/components/Ripple/Ripple.vue
lib/js/components/SectionHeader/SectionHeader.vue
lib/js/components/SelectList/SelectList.vue
lib/js/components/SurveyQuestions/SurveyQuestionOpenEnded/SurveyQuestionOpenEnded.vue
lib/js/components/SurveyQuestions/SurveyQuestionScale/SurveyQuestionScale.vue
lib/js/components/SurveyToggle/SurveyToggle.vue
lib/js/components/TabItem/TabItem.vue
lib/js/components/Tile/Tile.vue
lib/js/components/Toggles/CounterToggle/CounterToggle.vue
lib/js/components/Toggles/ToggleButton/ToggleButton.vue

https://v2.vuejs.org/v2/guide/components-props.html?redirect=true#Prop-Validation
It was all dead code. I suspect we might see some warnings in wnl-platform but they're hidden in production, so I think it's fine to merge without a big clean up.
Unfortunately I haven't found an eslint rule that would prevent this mistake.

Fix prop validators

---

lib/js/components/IconList/index.ts
lib/js/components/IconText/IconText.consts.ts
lib/js/components/IconText/IconText.stories.ts
lib/js/components/IconText/IconText.vue
lib/js/components/IconText/index.ts
lib/js/index.ts

https://www.figma.com/file/izQdYyiBR1GQgFkaOIfIJI/LMS---DS-Components?node-id=4833%3A81136&t=2Ya8MRi9vvdKstFR-4

IT-4974 | Rename IconList to IconText and update it

---

lib/js/components/SelectList/SelectList.stories.ts
lib/js/components/SelectList/SelectListItem/SelectListItem.vue

Fix for https://bethinkteam.slack.com/archives/C012R8RM3A4/p1677742854420669?thread_ts=1677512534.312019&cid=C012R8RM3A4

IT-5050 | Add placeholder to SelectListItem

---

lib/js/components/ProgressBar/ProgressBar.consts.ts
lib/js/components/ProgressBar/ProgressBar.stories.ts
lib/js/components/ProgressBar/ProgressBar.vue

Breaking changes:
* `numberOfLayers, colorScheme and color` props are removed -> migrate to `color` attribute in `ranges` props

IT-5088 | ProgressBar add badge + refactor range colors [breaking]

---

.storybook/main.js
lib/js/components/Modals/Modal/Modal.stories.ts
lib/js/components/Modals/Modal/Modal.vue
package.json
yarn.lock

https://wnl-design-system-preview.s3.amazonaws.com/IT-5087/index.html?path=/story/components-modals-modal--interactive

IT-5087 | Stop emitting close-modal when DsModal content is clicked

---

lib/js/components/Drawer/DrawerListItem/DrawerListItem.vue

https://bethinkteam.slack.com/archives/CFBLF5RGA/p1684762432292149

IT-5150 | Improve how DrawerListItem handles long value

---

lib/js/components/Drawer/DrawerSection/DrawerSection.vue

https://bethinkteam.slack.com/archives/C012R8RM3A4/p1684761537745629

IT-5150 | Expand DrawerSection by default

---

lib/js/components/Icons/Icon/Icon.consts.ts
lib/js/components/Ripple/Ripple.consts.ts
lib/js/components/Toggles/ToggleButton/ToggleButton.consts.ts
lib/js/components/Toggles/ToggleButton/ToggleButton.stories.ts
lib/js/components/Toggles/ToggleButton/ToggleButton.vue

- https://www.figma.com/file/izQdYyiBR1GQgFkaOIfIJI/LMS---DS-Components?type=design&node-id=6952-113818&t=qake8T49DPlWqO2M-4
- https://miro.com/app/board/o9J_knPnexA=/?moveToWidget=3458764546391058877&cot=14

IT-5130 | ToggleButton redesign

---

.github/workflows/build.yml
.github/workflows/storybook.yml

Run passed without deprecation warning: https://github.com/bethinkpl/design-system/actions/runs/5599236720

IT-5083 | upgrade github-pages-deploy-action

---

lib/js/icons/fontawesome.ts

We need it for https://bethink.atlassian.net/browse/IT-5258

IT-5258 | Add FA_ROTATE_LEFT icon

---

lib/js/components/Tile/Tile.shared.ts
lib/js/components/Tile/Tile.vue

https://bethinkteam.slack.com/archives/C012R8RM3A4/p1691068736436029

IT-5258 | Make Tile eyebrow optional while keeping min-height

---

lib/js/components/SelectList/SelectListItemTile/SelectListItemTile.vue

Fix after Ripple removal: https://github.com/bethinkpl/design-system/pull/308
Similar to https://github.com/bethinkpl/design-system/pull/310

IT-5395 | Fix SelectListItemTile spacing

---

dist/lib/js/components/Badges/Badge/Badge.consts.d.ts
lib/js/components/Badges/Badge/Badge.consts.ts
lib/js/components/Badges/Badge/Badge.stories.ts
lib/js/components/Badges/Badge/Badge.vue
lib/js/icons/fontawesome.ts

PR based on https://bethink.atlassian.net/browse/LMS-1361.
Questions:
- I know that we will be using only `xx-small` icon size in this case. Using any other icon size will break the component. Should component be responsive to changes in icon size? Maybe it's possible to freeze the size inside the Badge component to it will always remain this same?

LMS-1361 | add icon to Badge

---

lib/js/icons/fontawesome.ts

https://bethinkteam.slack.com/archives/C05T6D4EPHU/p1710417369528549

IT-5614 | Add new code icons

---

lib/js/components/Switch/Switch.vue

- clicking anywhere in switch changes its state
- prevent text from being selected

IT-5750 clicking anywhere in switch changes its state

---

.eslintrc.js
lib/js/components/Drawer/DrawerSection/DrawerSection.vue
lib/js/components/Form/Checkbox/Checkbox.vue
lib/js/components/Form/RadioButton/RadioButton.vue
lib/js/components/Form/SelectionControl/SelectionControl.sb.shared.ts
lib/js/components/Form/SelectionControl/SelectionControl.vue
lib/js/components/Headers/OverlayHeader/OverlayHeader.vue
lib/js/components/PopOver/PopOver.vue
lib/js/components/RichList/BasicRichListItem/BasicRichListItem.stories.ts
lib/js/components/RichList/BasicRichListItem/BasicRichListItem.vue
lib/js/components/RichList/RichListItem/RichListItem.stories.ts
lib/js/components/RichList/RichListItem/RichListItem.vue
lib/js/components/SelectionTile/SelectionTile.stories.ts
lib/js/components/SelectionTile/SelectionTile.vue
lib/js/typings.d.ts

We were using rules for Vue 2, my bad.
I clicked through all of the involved stories and they all seem fine to me. We're not using `update:isSelected` anywhere in the platform so that rename shouldn't be an issue.

Use plugin:vue/vue3-recommended for eslint

---

lib/js/components/PopOver/PopOver.vue

Revert popover span

---

yarn.lock

Due to https://github.com/node-fetch/node-fetch/pull/1699

Bump node-fetch version

---

lib/js/icons/fontawesome.ts

https://bethinkteam.slack.com/archives/C62T8MQ4U/p1720784654978559

Add FA_COMPASS_SOLID icon

---

lib/js/components/RichList/BasicRichListItem/BasicRichListItem.stories.ts
lib/js/components/RichList/BasicRichListItem/BasicRichListItem.vue
lib/js/components/RichList/GroupRichListItem/GroupRichListItem.stories.ts
lib/js/components/RichList/RichListItem/RichListItem.stories.ts
lib/js/components/RichList/RichListItem/RichListItem.vue

https://www.figma.com/design/izQdYyiBR1GQgFkaOIfIJI?node-id=10402-25980&m=dev#889059018

RichListItem | Rename meta slot to metadata

---

lib/js/components/Headers/OverlayHeader/OverlayHeader.vue
lib/js/components/Tooltip/Tooltip.vue
lib/js/primevue.ts
lib/styles/settings/_z-indexes.scss
package.json
vue.config.js

This reverts commit 18f058f1cb143d88d2b480b47cbb2ec5771a42d5.

IT-5903 Tooltip z-index and primevue as an external dependency

---

lib/js/components/RichList/RichListItem/RichListItem.vue

DR: https://bethinkteam.slack.com/archives/CFBLF5RGA/p1723815377699449

RichListItem | smooth animation on hover

---

lib/js/components/Image/Image.vue
lib/js/components/RichList/RichListItem/RichListItem.consts.ts
lib/js/components/RichList/RichListItem/RichListItem.vue

https://github.com/bethinkpl/wnl-platform/pull/5303
https://bethinkteam.slack.com/archives/C018TDAH5FW/p1729782649855729

IT-6031 | Improve RichListItem for media thumbnails

---

lib/js/components/DatePickers/DatePicker/DatePicker.vue

Decision: https://bethinkteam.slack.com/archives/CFBLF5RGA/p1731416100007329

IT-5861 don't hide date when loading

---

lib/js/components/Banner/Banner.vue

Fixes https://bethinkteam.slack.com/archives/C018TDAH5FW/p1732196037485519

LMS-2126 | Fix Banner width in flex containers

---

lib/js/icons/fontawesome.ts

Removing the replaced, now unused fa icons

Removing the replaced, now unused fa icons

---

lib/js/components/Modals/Modal/Modal.vue

Fix Modal height
